### ISSUE TITLE
Booksonic not starting up on current latest image

### ISSUE THREAD

**Issue by Tharic99** [linuxserver/docker-booksonic#11] opened 2019-04-30 14:18 UTC
After docker updated to the current `booksonic:latest` image, my Booksonic failed to start up completely. I deleted the image and pulled it down several times with no change. I then deleted the image and set my override to pull the `amd64-1.1.Beta1-ls12` image instead of latest

````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 30-config: executing... ,
[cont-init.d] 30-config: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
2019-04-30 09:29:42.138:INFO::main: Logging initialized @5436ms,
2019-04-30 09:29:42.204:INFO:oejr.Runner:main: Runner,
2019-04-30 09:29:43.701:INFO:oejs.Server:main: jetty-9.3.14.v20161028,
2019-04-30 09:29:51.151:INFO:oejs.AbstractConnector:main: Started ServerConnector@73d89e72{HTTP/1.1,[http/1.1]}{0.0.0.0:4040},
Exception in thread "main" java.lang.NoSuchMethodError: org.springframework.core.CollectionFactory.createConcurrentMapIfPossible(I)Ljava/util/Map;,
	at org.springframework.web.context.ContextLoader.<clinit>(ContextLoader.java:153),
	at org.springframework.web.context.ContextLoaderListener.createContextLoader(ContextLoaderListener.java:53),
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:44),
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:843),
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:533),
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:816),
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:345),
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1404),
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1366),
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:778),
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:262),
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:520),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:161),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:113),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:131),
	at org.eclipse.jetty.server.Server.start(Server.java:422),
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:105),
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61),
	at org.eclipse.jetty.server.Server.doStart(Server.java:389),
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68),
	at org.eclipse.jetty.runner.Runner.run(Runner.java:495),
	at org.eclipse.jetty.runner.Runner.main(Runner.java:536),
````

**Comment by Lerbaek** [comment] 2019-04-30 18:30
I have a similar issue with the ls14 release on an x64 Ubuntu, though my container manages to start. I just get a `404: Not found` when trying to access the web interface, and my Booksonic apps report that the server is offline. Pulling `1.1.Beta1-ls13` instead works as a workaround.

**Comment by thelamer** [comment] 2019-04-30 18:43
We are looking into this , but initially it looks like direct upgrades are not possible as clean containers work.

**Comment by thelamer** [comment] 2019-04-30 20:00
I have confirmed locally that a clean image will also not spinup even though our CI server was able to spin it up :
https://lsio-ci.ams3.digitaloceanspaces.com/linuxserver/booksonic/1.1.Release-ls14/index.html

**Comment by thelamer** [comment] 2019-04-30 21:52
So far between team members we have confirmed this bug on multiple systems. 
But it is working on current installations of unraid with some other systems with all things being equal. 
Still need more time to properly determine what is wrong.

**Comment by thelamer** [comment] 2019-05-01 03:12
This is resolved in the latest release please pull `:latest`

**Closed as completed by thelamer** 2019-05-01 03:12 UTC

**Comment by Lerbaek** [comment] 2019-05-01 06:17
Latest release confirmed working here, thanks!
