### ISSUE TITLE
Unable to add cover art

### ISSUE THREAD

**Issue by Sc0th** [linuxserver/docker-booksonic#22] opened 2020-04-22 10:20 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior

Ability to add cover art,

## Current Behavior

Trying to grab from last.fm or manually - when searching on last.,fm I do get results and tiled options, however if I choose one I get the error:

Sorry, an error occurred while searching for cover art.

If I try using a direct URL I also get the same

## Steps to Reproduce

1. Go to 'Change Cover Art' page
2. Search for related image e.g Treasure Island
3. Click on any returned image
4. see error - 'Sorry, an error occurred while searching for cover art.'

## Environment
**OS:** 
CentOS7 
**CPU architecture:** x86_64/arm32/arm64
x86_64  
**How docker service was installed:**      
In Kuberbnetes - can provide yaml if required.

## Command used to create docker container (run/create/compose/screenshot)

kubectl apply -f ....

## Docker logs

Not seeing any errors in the logs -

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1001
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-scripts: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-scripts: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-04-22 18:12:11.754:INFO::main: Logging initialized @587ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2020-04-22 18:12:11.761:INFO:oejr.Runner:main: Runner
2020-04-22 18:12:12.073:INFO:oejs.Server:main: jetty-9.4.24.v20191120; built: 2019-11-20T21:37:49.771Z; git: 363d5f2df3a8a28de40604320230664b9c793c16; jvm 1.8.0_242-8u242-b08-0ubuntu3~18.04-b08
2020-04-22 18:12:14.352:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2020-04-22 18:12:15.854:INFO:oejs.session:main: DefaultSessionIdManager workerName=node0
2020-04-22 18:12:15.854:INFO:oejs.session:main: No SessionScavenger set, using defaults
2020-04-22 18:12:15.856:INFO:oejs.session:main: node0 Scavenging every 660000ms
2020-04-22 18:12:15.960:INFO:oejshC.ROOT:main: Initializing Spring root WebApplicationContext
2020-04-22 18:12:28.160:INFO:oejshC.ROOT:main: Initializing Spring FrameworkServlet 'subsonic'
2020-04-22 18:12:30.470:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@61baa894{Subsonic Music Streamer,/,file:///tmp/jetty-0_0_0_0-4040-booksonic_war-_-any-2768942120323188991.dir/webapp/,AVAILABLE}{file:///app/booksonic/booksonic.war}
2020-04-22 18:12:30.557:INFO:oejs.AbstractConnector:main: Started ServerConnector@7a7b0070{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
2020-04-22 18:12:30.558:INFO:oejs.Server:main: Started @19398ms

**Comment by tobbenb** [comment] 2020-04-22 12:08
We do not test our containers on kubernetes, so we don't know if it works. Please supply the information on how you deployed the container.
Is the /config volume on direct filesystem or a shared one?

**Comment by Sc0th** [comment] 2020-04-22 23:53
Understood, it *should* - underlying docker version is 19.03.8
Filesystem is an NFS mount

Wanted to add that the images it find for itself add just fine, so presumably not an issue writing to storage, it only when trying to manually add, or pull from URL that it borks.

k8s yaml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: booksonic
spec:
  selector:
    matchLabels:
      app: booksonic
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        app: booksonic
    spec:
      containers:
      - name: booksonic
        image: prodregistry:5000/booksonic
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200Mi"
            cpu: "400m"
          limits:
            memory: "500Mi"
            cpu: "500m"
        env:
        - name: TZ
          value: "Asia/Singapore"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1001"
        ports:
        - containerPort: 4040
        volumeMounts:
        - mountPath: /config
          name: booksonic-config
        - mountPath: /audiobooks
          name: booksonic-audiobooks
      volumes:
      - name: booksonic-config
        hostPath:
          path: /appdata01/booksonic/config
          type: Directory
      - name: booksonic-audiobooks
        hostPath:
          path: /appdata01/booksonic/audiobooks
          type: Directory

**Comment by tobbenb** [comment] 2020-04-23 08:15
Remote mounts are usually creating problems and for /config we recommend to not use it, but use local storage instead. Sqlite and such doesn't work correctly on remote mounts.

If the images are added by booksonic, but doesn't work if you manually add it, it looks more like a bug in booksonic. Then you should report it to booksonic.

You can try to deploy booksonic on a standard docker system and local file system and see if the issue is still there. Then you'll know if it's a kubernetes issue or not.

**Comment by Sc0th** [comment] 2020-04-23 08:18
sqlite works just fine on numerous other dockers, I run over 50 dockers across the same infrastructure and have observed no issues with any other pods. Not to worry, thanks for your time.

**Comment by tobbenb** [comment] 2020-04-23 08:22
We have observe a lot of issues with sqlite and remote mounts and fuse filesystems. 
If it works for you, great.

**Comment by Sc0th** [comment] 2020-04-23 08:29
Was not aware fuse filesystems were involved, where does that come into play? Also if this is related how might it be that images grabbed automatically are saved without issue?

**Comment by tobbenb** [comment] 2020-04-23 10:36
I think you misunderstood me. I'm talking about areas were sqlite have issues and fuse file systems is one, along with remote file systems.

I don't even know if booksonic use sqlite.

**Comment by hjone72** [comment] 2020-07-07 01:03
I believe this error could be related to a change with Jetty introduced in https://github.com/linuxserver/docker-booksonic/tree/1.1.ReleaseFix-ls47 that only started causing problems with Booksonic 1.2.

I can successfully download cover art, and generally access the internet (podcast download) up until the swap to v1.2. This could be a booksonic issue however I think it's actually a combination of Jetty and Booksonic.

Running the latest release before 1.2 fixes the problem for me. I don't know enough about Java to investigate further.

**Comment by aptalca** [comment] 2020-07-07 03:34
If 1.2 started causing issues, you should probably report it upstream to booksonic. The jetty update was more than 6 months ago

**Comment by hjone72** [comment] 2020-07-07 04:46
Yeah happy to do that. Just wasn't sure if it was related to the container as the log specifically references Jetty.

edit:
Yep, does look like it's an upstream issue. Sorry for the mistake.

**Comment by j0nnymoe** [comment] 2020-07-07 07:42
Considering https://github.com/popeen/Popeens-Subsonic is now marked as deprecated, I don't think there is much hope that it'll get fixed.

**Comment by j0nnymoe** [comment] 2020-07-15 08:00
Closing as no further reply.

**Closed as completed by j0nnymoe** 2020-07-15 08:00 UTC
